package com.embaradj.velma;

import com.embaradj.velma.models.Job;
import com.embaradj.velma.results.SearchHit;
import javax.swing.*;
import java.awt.*;

/**
 * Menu to show details about a HVE or a Job, or Help text
 */
public class DetailsForm extends JFrame {
    private Settings settings = Settings.getInstance();
    private JTextField detailsTextField;
    private JPanel mainPanel;
    private JTextArea textArea;
    private JButton closeBtn;
    private JTextPane textPane1;
    private JScrollPane scrollPane1;

    /**
     * Overloaded constructor in order to use the same form for both SearchHits and help menu
     */
    public DetailsForm() {
        $$$setupUI$$$();
        setContentPane(mainPanel);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pack();
        setLocationRelativeTo(null);    // Position the frame in the center of the screen
        setVisible(true);
        closeBtn.addActionListener(e -> {
            dispose();
        });
    }

    public DetailsForm(SearchHit searchHit) {

        this();     // Overloaded constructor

        boolean isHve = (searchHit.getType() == "hve");
        setTitle((isHve ? "HVE: " : "Job: ") + searchHit.getTitle());
        textArea.setText(searchHit.getDescription());

        // Just for some troubleshooting..
        if (settings.debug() && !isHve) {
            Job job = (Job) searchHit;
            System.out.println(job.getId());
        }
    }

    public DetailsForm(String title, String contents) {
        this();     // Overloaded constructor
        setTitle(title);
        textArea.setText(contents);
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setMinimumSize(new Dimension(200, 200));
        mainPanel.setName("mainP");
        mainPanel.setPreferredSize(new Dimension(600, 400));
        scrollPane1 = new JScrollPane();
        scrollPane1.setPreferredSize(new Dimension(600, 400));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 100.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 5, 5, 5);
        mainPanel.add(scrollPane1, gbc);
        textArea = new JTextArea();
        textArea.setEditable(false);
        textArea.setLineWrap(true);
        textArea.setMargin(new Insets(20, 20, 0, 0));
        scrollPane1.setViewportView(textArea);
        closeBtn = new JButton();
        closeBtn.setText("Close");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 5, 5, 5);
        mainPanel.add(closeBtn, gbc);
        textPane1 = new JTextPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(textPane1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
